version: '3'
services:
  xinference:
    container_name: xinference
    hostname: xinference
    image: xprobe/xinference:v0.12.1-cpu
    ports:
      - "9997:9997"
    volumes:
      - ./volumes/xinference/models:/root/.xinference:rw  # 持久化模型文件
      - ./volumes/xinference/start_services.sh:/root/start_services.sh
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
      - XINFERENCE_HOME=/root/.xinference  # 设置 Xinference 的默认目录
    command: ["bash", "/root/start_services.sh"]
